### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by HostFat** [greenaddress/GreenBits#1]
There are some strings that still need to be translated in italian language, and maybe it's the same for other languages.

I can be a good idea to open another project on Crowdin / Transifex, to make it easier even for outsiders.

**Comment by greenaddress** [comment]
fixed in 7121ec469a3de04df6f5e3522b38ffefda4e45ff

We still need to make the files available in Crowdin or Transifex so keeping it open

**Comment by greenaddress** [comment]
Added translation files to Transifex, https://www.transifex.com/organization/greenaddress/dashboard/greenbits
