### ISSUE TITLE
Forget Mnemonic 

### ISSUE THREAD

**Issue by mepawan** [greenaddress/GreenBits#128]
Hi,

I forgot my mnemonic. I only remember my bitcoin address and email associated with my account. 

Can you please help me to login by email or help me to recover/update my mnemonic using my email?

Thanks,

**Comment by jgriffiths** [comment]
Hi @mepawan,

For security, the GreenAddress service does not store your mnemonics in any form at all. If they were stored on the server they could be used to steal your coins.

As explained when you created your mnemonics, you must securely back them up. If you have GreenBits or another client installed and setup with PIN login then you can display your mnemonics from the settings menu after logging in with the PIN. If not, and you have no backup of your mnemonics then I'm sorry, your coins are inaccessible.

I am closing this issue as it does not relate to GreenBits. If you have any further questions, please see https://greenaddress.it/en/support.html and email them using the email address provided there.

Regards
Jon
