### ISSUE TITLE
GreenBits crashes during QR code recognition

### ISSUE THREAD

**Issue by Stemby** [greenaddress/GreenBits#137]
Hi,
trying to send an amount, just after the QR code is found (it becomes green) GreenBits crashes.

I'm using version 1.87 taken from F-Droid on Android 6.0 (ulefone Vienna).

**Comment by greenaddress** [comment]
Thanks for the report.

Could you try to reproduce this with version 1.89? It is also available via F-Droid and it should fix a number of crashes which are likely to include this.

**Comment by Stemby** [comment]
Fixed in 1.89, thanks!
