### ISSUE TITLE
[UI] monetary formatting

### ISSUE THREAD

**Issue by 5chdn** [greenaddress/GreenBits#166]
Hi there. I'm using GreenBits 1.91 from F-Droid and would like to suggest some improvements in the user interface.

I can not get the local builds running, so I will try to simply point out the code fragement which are probably important for what I describe.
- Space between currency symbol and the amount is missing, e.g., [ListTransactionsAdapter.java:L57](https://github.com/greenaddress/GreenBits/blob/master/app/src/main/java/com/greenaddress/greenbits/ui/ListTransactionsAdapter.java#L57) vs. [ListTransactionsAdapter.java:L59](https://github.com/greenaddress/GreenBits/blob/master/app/src/main/java/com/greenaddress/greenbits/ui/ListTransactionsAdapter.java#L59): `"bits "` comes with space, but somehow `R.string.fa_btc_space` not; is it possible to add a space behind the latter?
- If possible, please set fixed number of decimals, i.e., always 8 decimals for BTC or 2 decimals for _bits_. Is that possible? I had a look into [MonetaryFormat.java:354](https://github.com/greenaddress/GreenBits/blob/master/bitcoinj/core/src/main/java/org/bitcoinj/utils/MonetaryFormat.java#L354) and it looks like a feature to trim trailing zeros. This makes the amounts _jumping_ around in the interface (as they are aligned right) and it's not obvious on first glance which are big and which are small amounts. A cool way would be not to trim them but to style them in a very light grey. What do you think?

It also sometimes looks very strage, if you have fiat currency values with only one decimal digit, e.g., `$ 210.4`.

Thanks
5chdn

**Comment by greenaddress** [comment]
@5chdn thanks for the feedback, we'll look into it and get back.

Meanwhile is there anything we can help with to get it to build locally? The .travis file may be useful as it shows some of the dependencies. Feel free to open an issue if you have some logs.

**Comment by 5chdn** [comment]
I was missing Swig. Maybe it's useful to hint in readme? ;-)

Also it was complaining about missing libwally. Had to build that first. Stay tuned.

**Comment by jgriffiths** [comment]
Hi @5chdn, thanks for report these issues. The documentation and missing space should be available in the next release in a couple of days. Changing the number formatting will require a little more work so we will look into this for a later release. The code to format numbers is due to be refactored to share a single which will make experimenting with different formatting options easier. We have a few technical improvements that we need to push first however.

**Comment by greenaddress** [comment]
hello @5chdn - release 1.92 has been tagged and published, on F-Droid you will have to wait for it to pick up and within 48 hours it should be available

**Comment by greenaddress** [comment]
closing as issue should be at fixed. If not please feel free to reopen.
