### ISSUE TITLE
sweep is too slow only in mainnet

### ISSUE THREAD

**Issue by zidagar** [greenaddress/GreenBits#196]
The Greenaddress site and GreenBits are too slow to sweep the private key, only in mainnet and not in testnet.
I think the problem is in the WAMP call "prepare_sweep_social"; this call is long more than 1 minute.

Please check the server code to confirm the bug server-side. Thank you

**Comment by jgriffiths** [comment]
Hi @ zidagar,

We have some speed improvements to this functionality and the backend in general in testnet, but I think the cause of the slowness in this case is elsewhere. Can you point me at a mainnet sweep tx that was slow for you, so we can investigate?

**Comment by jgriffiths** [comment]
This should be fixed by our new backend sweeping code.
