### ISSUE TITLE
org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject

### ISSUE THREAD

**Issue by nicocesar** [greenaddress/GreenBits#198]
After I successfully log in, I try so send and I get the following message pop up: 

org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject

Seems like som expected JSON result is hitting an HTML page 

Tried Wifi and LTE network.

Android 6.0.1  in a Samsung S6

**Comment by greenaddress** [comment]
Hi, 

indeed this is a temporary intermittent backend issue, apologies. The chrome app is currently not suffering from this issue as it doesn't use the calls that fails for GreenBits here.

We are working as fast as possible on a solution. If you need to move the funds fast please use the Chrome app or the Cordova app for android

thanks

**Comment by greenaddress** [comment]
@nicocesar this has been resolved.

Please let us know if you encounter any issue.

Regards

**Comment by nicocesar** [comment]
Working all right. Thanks,
