### ISSUE TITLE
Fingerprint support

### ISSUE THREAD

**Issue by bitcoinuser** [greenaddress/GreenBits#203]
Hi, 

I hate have to type PIN all time to login on greenbits. Could you support fingerprint?

Thanks.

**Comment by greenaddress** [comment]
Hello,

We already support fingerprint but it requires you to enable it at the Android level. GreenBits will then prompt you to use the normal PIN or the Android Native Authentication.

Let us know if this helps!

Thanks

**Comment by bitcoinuser** [comment]
There are other apps that works, but greenbits doesn't give me the option to use fingerprint. I always need to insert the PIN to access greenbits on Android.

**Comment by bitcoinuser** [comment]
On greenbits app permission details on android, there is NO, (use fingerprint hardware).
I see this on other apps (on android permission details)

**Comment by greenaddress** [comment]
reset the PIN and when you do select "Native authentication", then it will use whatever your android uses which includes fingerprint hardware if that's what you use.

**Comment by bitcoinuser** [comment]
Hi. 

Worked.

Thanks.
