### ISSUE TITLE
Trying to spend with Keepkey crashes greenbits

### ISSUE THREAD

**Issue by RyanSinger** [greenaddress/GreenBits#206]
Hi!

I am trying to use my keepkey+greenaddress wallet on my phone with GreenBits. Login works perfectly, but when I try to spend a transactions PIN screen shows up as normal on the keepkey but GreenBits crashes. Help!

**Comment by jgriffiths** [comment]
Hi,

Is it possible for you to get an adb log from the phone? If so please email it to info@greenaddress.it - in the meantime we will try to reproduce here, thanks.

**Comment by greenaddress** [comment]
@RyanSinger we deprecated support for KeepKey as it does not have support for segwit and in general it seems bitcoin support is not the top priority. Closing.
