### ISSUE TITLE
Upon showing a new address and receiving funds user has to move to tx list to see any activity

### ISSUE THREAD

**Issue by greenaddress** [greenaddress/GreenBits#208]
Currently if a user shows an address to someone and receives some funds on it he won't be aware of the new transaction until he moves to the middle tab/transaction list.

One option could be to show a notification if the app is open and a new transaction is received, another option could be to move automatically to the transaction list upon receiving an inbound transaction.

The former may be less intrusive (say in case when one wants to receive multiple transactions) but ideally users shouldn't receive multiple transactions on the same address so if we were to just show a notification we ought to also refresh/change the address in the Receive tab to avoid receiving multiple transaction on the same address.

**Comment by jgriffiths** [comment]
We could automatically move only when the tx was sent to the address being shown, and show a notification otherwise.

**Comment by greenaddress** [comment]
yep, sounds good

**Comment by jgriffiths** [comment]
Fixed by PR #278
