### ISSUE TITLE
In the event of a hard fork, will both coin types be accessible for GB/GA wallets?

### ISSUE THREAD

**Issue by crystalneth** [greenaddress/GreenBits#220]

**Comment by greenaddress** [comment]
Sorry for the late reply.

It depends on the kind of fork and whether it supports replay protection or not and how it does that.

Recently we posted our position on contentious fork on our blog here https://blog.greenaddress.it/2017/03/27/greenaddress-position-on-contentious-forks/

**Comment by jgriffiths** [comment]
Please also see our position explained at https://blog.greenaddress.it/2017/07/24/uasf-segwit-softfork-enforcement/
