### ISSUE TITLE
Question about use with Tor

### ISSUE THREAD

**Issue by AlfaOmega33** [greenaddress/GreenBits#225]
Hello. I would like to ask you something: 

1) if I use Orbot (+ transparent proxy with Root permission), the entire traffic will be filtered through Tor, or "simply" my identity will be masked?

2) using Orbot, I can send bitcoin in other portfolios reached exclusively through Tor (".onion" wallet)?

**Comment by greenaddress** [comment]
We support Orbot's Socks5 however we haven't tried Orbot on a device with root so we haven't tested transparent proxy.

I don't get the second question however if you do set the Socks5 for Orbot we also support using GreenAddress' onion address (same as the one in our FAQ)

**Comment by AlfaOmega33** [comment]
I understand. Thank you for answered.
