### ISSUE TITLE
RBF, when trying to rbf a tx that is already confirmed 

### ISSUE THREAD

**Issue by greenaddress** [greenaddress/GreenBits#232]
![screenshot_1493217949](https://cloud.githubusercontent.com/assets/5269298/25440519/9bb968c4-2a97-11e7-9e47-89d7e3250ea5.png)

When trying to opt-in RBF a tx that has already been confirmed the user is presented with an internal error. The app should instead tell the user the transaction has already been confirmed.

**Comment by jgriffiths** [comment]
Note I get 'missing prevout' when I try this.

**Comment by jgriffiths** [comment]
Implemented in the next (GDK-based) release.
