### ISSUE TITLE
Phone authentication [bug] 

### ISSUE THREAD

**Issue by herbat** [greenaddress/GreenBits#246]
I'm not exactly sure of the reason, but after I changed phones(from a non-android, Blackberry Passport to an LG G5), my phone authentication method isn't working. No number change, I even use the same SIM. 
The 2FA settings don't even show up(meaning the GUI objects don't show, it stays blank if I try to set up a new method of 2FA), and the GreenAddress client I am using says 'Internal error'. I guess this is a backup problem, because just a few days ago, the phone auth was working perfectly.  
I use GreenBits client 1.96. This issue occurred with the Chrome Extension and Cordova app as well, so it's probably a more serious issue.

**Comment by jgriffiths** [comment]
This was a backend issue with our SMS/phone provider which should now be resolved.
