### ISSUE TITLE
I have a snapshot of my mnemonic

### ISSUE THREAD

**Issue by Avaris2409** [greenaddress/GreenBits#253]
When it said my pin wasn't working after making several transactions in the last couple days in the in my mnemonic like it asked accept it said it need to be 24 or 26 words which mine was not that.

**Comment by Avaris2409** [comment]
is green address being hacked? And where do you actually go for support on this issue?

**Comment by greenaddress** [comment]
Hi,

The app would ask for 24 or 27 words long mnemonics. Generally if your mnemonic is not 24 or 27 words long it means it was created elsewhere.

Have you used hardware wallets in the past with GreenAddress/GreenBits?

For support you can email us at info@greenaddress.it, please provide a link to this issue for reference.
To our knowledge GreenAddress is not currently being hacked.

Thanks

**Comment by greenaddress** [comment]
Closing, feel free to email us or re-open in case this is still an issue.
