### ISSUE TITLE
invalid phone number: unknown country code or invalid number format

### ISSUE THREAD

**Issue by Jona033** [greenaddress/GreenBits#268]
Dear Sir/Madam,

for 6 months i have my own bitcoin account and when i payed with BTC i always got my code through sms. web interface now told me my phone number was invalid. I have made multiple receive and send transactions through phone client before and I have changed nothing. I probably entered my phone number in +-country-code-and-number format or as 00-country-code-and-number. And when I was setting up my account, it didn't tell me two or more 2FA options were recommended. Now I can log in but I can't send BTC. Please help quick i need to pay important bills!

kind regarts,

Jona Smidt

**Comment by jgriffiths** [comment]
Hi,

Please send the phone number you are using to info@greenaddress.it and we will take a look at the problem, our SMS provider recently updated their number validation so it is likely that the format just needs adjusting.
