### ISSUE TITLE
Setting pin timeout to zero causes looping pin entry request

### ISSUE THREAD

**Issue by wintercooled** [greenaddress/GreenBits#273]
If you enter zero as the timeout the app just keeps asking for your pin. There is no way to then get around this.

Suggest you don't allow 0 to be set.

**Comment by jgriffiths** [comment]
Hi,

This will be fixed in tomorrows release.

**Comment by wintercooled** [comment]
Thanks.

**Comment by jgriffiths** [comment]
Fix is merged just waiting for a release (a day or so, we have another fix to roll up with the release).

**Comment by wintercooled** [comment]
Cheers. Will it undo the fact that 0 is saved in my config as well as just
prevent it from being set it the future? Would love to have access to your
app again. I started using it because of its Segwit support you see. 😁

**Comment by jgriffiths** [comment]
Hi, it treats timeouts less than 1 minute as 1 minute so you can login and go to settings to update it rather than being immediately logged out.

**Comment by jgriffiths** [comment]
If you need to transact before we release you can always use the web wallet at https;//www.greenaddress.it/wallet

**Comment by wintercooled** [comment]
Thanks, I've already used greenaddress to move the Bitcoin. Going to a
conference in Paris tomorrow so needed something accessible for that. Will
move back to greenbits when I'm back.

Cheers for the updates 😁


On 7 Sep 2017 21:18, "jgriffiths" <notifications@github.com> wrote:

If you need to transact before we release you can always use the web wallet
at https;//www.greenaddress.it/wallet

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/greenaddress/GreenBits/issues/273#issuecomment-327916219>,
or mute the thread

**Comment by wintercooled** [comment]
Latest release fixed it - as you said.

Thanks,
Matt.
