### ISSUE TITLE
Network Configuration does not open, throws error

### ISSUE THREAD

**Issue by nothingmuch** [greenaddress/GreenBits#289]
Steps to reproduce:

1. starting from the "Welcome to Greenbits" screen, press the vertical ... menu button
2. select "Network Configuration"
3. select "(i) Network configuration" from the menu

This results in the following error:

> Unable to contact the GreenAddress service. Please check your network connection and wait to be reconnected.

and returns to the welcome screen

I experienced this with android 7, upgraded to 8, and am still experiencing this.

Version 2.02, installed from play store

Update to add: downgrading to 1.99 from f-droid worked around this issue for me

**Comment by jgriffiths** [comment]
Hi,

This will be fixed in the next release, thanks for the report.
