### ISSUE TITLE
Add support for sending to BIP173 addresses

### ISSUE THREAD

**Issue by Walter-Bishop** [greenaddress/GreenBits#293]
[BIP173](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki) ("bech32") enables native segwit transactions on the Bitcoin network. Using it will allow for smaller on-chain transactions. For bech32-addresses to gain adoption, wallet support is needed.

Please add support for sending to BIP173 addresses.

**Comment by jgriffiths** [comment]
This is done and will be available in the next release.
