### ISSUE TITLE
How are Green Bits' Segwit addresses derived?

### ISSUE THREAD

**Issue by bjarnemagnussen** [greenaddress/GreenBits#304]
I understand from here [https://github.com/greenaddress/GreenBits/issues/269] that Green Bits does not support BIP49. But how are the Segwit addresses for a "normal" (non-multisig) Green Bits installation derived?

**Comment by jgriffiths** [comment]
Hi,

We believe we answered this on https://reddit.com/r/greenaddress, if not please ask there as this issue tracker is only for tracking GreenBits issues, thanks.
