### ISSUE TITLE
wallycore.jar does not exist

### ISSUE THREAD

**Issue by huanleyuan** [greenaddress/GreenBits#329]
Transform output file \GreenBits-master\app\libwally-core\src\swig_java\wallycore.jar does not exist

**Comment by jgriffiths** [comment]
Hi, can you give some more detail, specifically what were you doing to get this error?

**Comment by huanleyuan** [comment]
C:\Users\user\Desktop\bt\GreenBits-master>gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:btctestnetDebugCompileClasspath'.
> Failed to transform file 'wallycore.jar' to match attributes {artifactType=android-classes} using transform JarTransform
   > Transform output file C:\Users\user\Desktop\bt\GreenBits-master\app\libwally-core\src\swig_java\wallycore.jar does not exist.

**Comment by jgriffiths** [comment]
You need to read the instructions in the README, specifically:

To fetch and install the pre-built naitive libraries, run:

./app/fetch_libwally_binaries.sh
