### ISSUE TITLE
Screen flicker happend with error log on production debug build.

### ISSUE THREAD

**Issue by abewangm** [greenaddress/GreenBits#330]
07-09 17:44:10.325 26720 26720 E AbstractFuture: RuntimeException while executing runnable CallbackListener{com.greenaddress.greenbits.ui.GaActivity$1@965fab8} with executor MoreExecutors.directExecutor()
07-09 17:44:10.325 26720 26720 E AbstractFuture: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
07-09 17:44:10.325 26720 26720 E AbstractFuture: 	at com.greenaddress.greenapi.WalletClient.isTwoFactorResetDisputed(WalletClient.java:893)
07-09 17:44:10.325 26720 26720 E AbstractFuture: 	at com.greenaddress.greenbits.GaService.isTwoFactorResetDisputed(GaService.java:1432)
07-09 17:44:10.325 26720 26720 E AbstractFuture: 	at com.greenaddress.greenbits.ui.TabbedMainActivity.launch(TabbedMainActivity.java:276)
07-09 17:44:10.325 26720 26720 E AbstractFuture: 	at com.greenaddress.greenbits.ui.TabbedMainActivity.onCreateWithService(TabbedMainActivity.java:122)
07-09 17:44:10.325 26720 26720 E AbstractFuture: 	at com.greenaddress.greenbits.ui.GaActivity$1$1.run(GaActivity.java:63)
07-09 17:44:10.325 26720 26720 E AbstractFuture: 	at android.app.Activity.runOnUiThread(Activity.java:6190)
07-09 17:44:10.325 26720 26720 E AbstractFuture: 	at com.greenaddress.greenbits.ui.GaActivity$1.onSuccess(GaActivity.java:58)
07-09 17:44:10.325 26720 26720 E AbstractFuture: 	at com.greenaddress.greenbits.ui.GaActivity$1.onSuccess(GaActivity.java:55)
07-09 17:44:10.325 26720 26720 E AbstractFuture: 	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1347)
07-09 17:44:10.325 26720 26720 E AbstractFuture: 	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:398)
07-09 17:44:10.325 26720 26720 E AbstractFuture: 	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1027)
07-09 17:44:10.325 26720 26720 E AbstractFuture: 	at com.google.common.util.concurrent.AbstractFuture.addListener(AbstractFuture.java:672)
07-09 17:44:10.325 26720 26720 E AbstractFuture: 	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.addListener(AbstractFuture.java:107)
07-09 17:44:10.325 26720 26720 E AbstractFuture: 	at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1322)
07-09 17:44:10.325 26720 26720 E AbstractFuture: 	at com.google.common.util.concurrent.Futures.addCallback(Futures.java:1276)

**Comment by abewangm** [comment]
Issue happend on the line below,
  final boolean isActive = mLoginData.get("reset_2fa_active");
-------------------------------------------------------------------------------------------
   public Integer getTwoFactorResetDaysRemaining() {
        final boolean isActive = mLoginData.get("reset_2fa_active");
        return isActive ? mLoginData.get("reset_2fa_days_remaining") : null;
    }

    public boolean isTwoFactorResetDisputed() {
        return mLoginData.get("reset_2fa_disputed");
    }

**Comment by jgriffiths** [comment]
Hi,

The master branch contains changes for our next release, which cannot yet be run against production mainnet until it is upgraded.

In general you should build and run the last tagged revision as this represents the currently released code. We will be upgrading the backend this weekend and releasing the clients however, so mast as-is should start working for you by monday.

**Comment by abewangm** [comment]
Confirmed that issue got addressed in latest master branch source.
