### ISSUE TITLE
Allowing more than one trusted peer for SPV

### ISSUE THREAD

**Issue by gabridome** [greenaddress/GreenBits#51]
In the actual form only one trusted node is allowed unger settings / SPV synchronization.

For backup and verification purposes it would be wise to allow plural nodes connections.

One may be down or not in sync with the other (or with the rest of the network). If these are trusted peers it could be a signal that something is not going as expected too.

Probably the best syntax could be a comma separated one for simplicity.

**Comment by greenaddress** [comment]
added support for multiple trusted nodes by ed25559b2a7e86d0353034317572cc3be08656da and 8dfc3e45d4e9e7ce1502c2a10920e022275a7e04

Warning: if you use mutiple mixed onion and clearnet nodes both will use tor, which makes MITM possible to clearnet nodes.

**Comment by gabridome** [comment]
Thank you. Great job @greenaddress.
