### ISSUE TITLE
Include a Changelog Link, within the F-Droid App', on Info' Page; 1.64.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [greenaddress/GreenBits#53]
Include a Changelog Link, within the F-Droid App', on Info' Page.  Not present, as of: 1.64.

**Comment by krt16s** [comment]
Once there is a changelog in the repo (or somewhere else I am not aware of), ping me to get it included in fdroid.

**Comment by greenaddress** [comment]
@locutis-of-borg-1999 @krt16s can you clarify what would work for you?

At the moment we are using the github release page to keep track of tag/versions and change log.

For example https://github.com/greenaddress/GreenBits/releases

We usually link this from the play store.

Would it be sufficient to update the Fdroid page to provide a link to the release page on github or do you want us to add a link to the release changelog within the app? 

Both are fine i just want to understand what is your preference.

Or do you want something different and I misunderstood the request?

**Comment by krt16s** [comment]
The releases page will do.. I keep forgetting that GitHub does not only use tags for..well tagged commits. Sorry for the noise. I hope https://gitlab.com/fdroid/fdroiddata/commit/c27b644cafaca8a9de9e87f221b7aa41bbc3a273 closes this issue.

**Comment by greenaddress** [comment]
@krt16s No problem, thank you for updating the page and for the great work on F-Droid!
