### ISSUE TITLE
changing PIN

### ISSUE THREAD

**Issue by anarcat** [greenaddress/GreenBits#57]
is it possible to change the PIN on the app?

**Comment by greenaddress** [comment]
It is possible but GreenBits currently doesn't support it. The GreenAddress Chrome app supports it and we will be looking to add support for it in GreenBits, thank you for your feedback.

**Comment by anarcat** [comment]
Awesome, thanks for the fast response!

**Comment by greenaddress** [comment]
added in 913e661eafc06d8a751db9cb92df4b03a854248f

**Comment by gabridome** [comment]
there's a workaround but it need a reinstall to be made.

You can erase your data (an uninstall would do it) and when you enter your Mnemonic on the new installation a new pin is required.

**Comment by greenaddress** [comment]
@gabridome i think you're getting confused. The fix above adds the ability to change PIN from settings (so not a work around). It hasn't been released yet, it will be released in 1.78

**Comment by greenaddress** [comment]
yes correct that's the work around for now but from 1.78 onwards you'll be able to change it from settings
