### ISSUE TITLE
App crash when I send bits

### ISSUE THREAD

**Issue by gitloled** [greenaddress/GreenBits#60]
Hi, I use Android 4.2.2 on Samsung S3 mini.
Thanks for any help!

**Comment by greenaddress** [comment]
thank you

Did you send the crash report when it crashed?

Is that version GreenBits 1.77?

**Comment by gitloled** [comment]
No I did not send the crash report.
It is version 1.75 from F-Droid

**Comment by greenaddress** [comment]
ok i'm not sure you can send a crash report via F-Droid

We have version 1.77 in F-Droid since a couple of days ago, any chance you could see if you have problems with that version?

Thanks

**Comment by gitloled** [comment]
actually version 1.77 solve my problem !
Thanks

**Comment by greenaddress** [comment]
great to hear, thanks for closing the issue
