### ISSUE TITLE
[UI] Add padding to button

### ISSUE THREAD

**Issue by Kirvx** [greenaddress/GreenBits#61]
![screenshot_20160424-135636](https://cloud.githubusercontent.com/assets/6627786/14767428/d741a8b4-0a24-11e6-8370-1cacbf048d40.png)

**Comment by greenaddress** [comment]
thanks! Having a look..

**Comment by greenaddress** [comment]
fixed in e24b257e380ff8bb5ec973d606198ed4a69909b7
