### ISSUE TITLE
[UI] Word problem

### ISSUE THREAD

**Issue by Kirvx** [greenaddress/GreenBits#62]
### " Nouvelle " is cut
![screenshot_20160424-135555](https://cloud.githubusercontent.com/assets/6627786/14767445/508b1b92-0a25-11e6-941a-5a1f10d2277d.png)

**Comment by greenaddress** [comment]
On it.

**Comment by greenaddress** [comment]
fixed it in 51da946a2e04fcc9c0135cb1cc095e1b84c5df1a
