### ISSUE TITLE
Error:Configuration with name 'default' not found.

### ISSUE THREAD

**Issue by davidkhala** [greenaddress/GreenBits#73]
When using gradle 2.13 to sync there is an error such in title
source/target compatiliblity 1.7
build tool version: 23.0.3
compile SDK version: API 23

**Comment by greenaddress** [comment]
Did you init your submodules?

Are you using the same version as travis (which seems to work fine?)

**Comment by davidkhala** [comment]
@greenaddress not yet, I just follow the readme.md guide... 
I will try and investigate it a little bit and will reply later.
And BTW who is travis and could you provide a link about how doe his solution work?

**Comment by greenaddress** [comment]
If you do all the steps in the README you should not have problems.

Travis is our CI (Continuous Integration) - you can find it here https://travis-ci.org/greenaddress/GreenBits

**Comment by davidkhala** [comment]
I tried to follow README again and get problem when doing:
Cross-compile the native libraries:
$ pushd app && ./prepare_fdroid.sh && popd

the output show as follow, 

Initialising:
aarch64-linux-android-4.9 arm-linux-androideabi-4.9 mips64el-linux-android-4.9 mipsel-linux-android-4.9 x86-4.9 x86_64-4.9
============================================================
./autogen.sh: 3: ./autogen.sh: autoreconf: not found

then I run $ sudo apt-get install autoconf 
then run again but still failed.

configure.ac:20: installing 'build-aux/compile'
configure.ac:5: installing 'build-aux/config.guess'
configure.ac:5: installing 'build-aux/config.sub'
configure.ac:9: installing 'build-aux/install-sh'
configure.ac:9: installing 'build-aux/missing'
Makefile.am:3: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:3:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:3:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
Makefile.am:3:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:3:   its definition is in aclocal's search path.
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
autoreconf: automake failed with exit status: 1

Actually it might be my fault as a linux newbie

**Comment by greenaddress** [comment]
Looks like now you need to install the jdk for configure to pick up the jni header files (yes both autoconf and libtool were needed, likely if you haven't installed it you will also need build-essential)

**Comment by greenaddress** [comment]
@davidkhala are you still having this issue? If not, can you or I close it?

**Comment by davidkhala** [comment]
@greenaddress Sorry for that for our project we have moved to customize bitcoin-core and no more attention on GreenBits, thus whether to close it is up to you. Thanks!

**Comment by greenaddress** [comment]
thanks
