### ISSUE TITLE
UI suggestions

### ISSUE THREAD

**Issue by bitcoinuser** [greenaddress/GreenBits#89]
Hi, I really like Greenbits app. Here are some sugestions to the UI that I would like to see implemented:

1- I would like to see the account name removed from the top. Instead of show account name, should show account balance. Something like Circle app.

![screenshot_2016-08-21-18-00-03](https://cloud.githubusercontent.com/assets/1178856/17839830/1f7cf102-67cb-11e6-8174-c5308e041657.png)

2- I Like the account button of on bottom right. When I open it, I would like to see the account names, but I would like to see the balance of each account too, and which account is selected.

![screenshot_2016-08-21-18-03-32](https://cloud.githubusercontent.com/assets/1178856/17839844/8c28eba8-67cb-11e6-8bda-641375a36b40.png)

3- I like Greenbits color, but I think should have an option to change the colors of the app. Something like what Copay app has.

**Comment by greenaddress** [comment]
dear @bitcoinuser thanks for the feedback

in the branch ui_improvements_89 we just pushed some commits that should address 1 (optional) and 2.

Would you like to participante in some early beta testing?

For 3 it will take a while longer but we do want to provide customisation options.

**Comment by bitcoinuser** [comment]
Great,

yes I would like to participate in early beta testing.

Thanks.

**Comment by greenaddress** [comment]
@bitcoinuser changes are already merged and beta testing release coming, great, thank you!

**Comment by greenaddress** [comment]
@bitcoinuser you can find the apk in beta testing here https://github.com/greenaddress/GreenBits/releases/tag/r1.86_betatest

**Comment by jgriffiths** [comment]
Hi @bitcoinuser,

The next release of the app includes further UI changes including making the 'account in title' option more usable and aligning the the transaction amount display. These are all the UI changes that are planned for the immediate future.

I have noted your suggestion to allow changing the UI colors and will implement this in the future when time permits. For now I am closing this issue as I believe all the other items you raised have now been addressed. Many thanks for taking the time to make these suggestions.
